routes/web.php
<?php

Route::get('payeer_902403141.txt', function () { return '902403141'; });

Route::group(['prefix' => LaravelLocalization::setLocale()], function() {

    Auth::routes();

    Route::get('/', 'HomeController@index')->name('welcome');
    Route::get('/started', 'HomeController@started')->name('started');
    Route::get('/faq', 'HomeController@faq')->name('faq');
    Route::get('/rules', 'HomeController@rules')->name('rules');
    Route::get('/reviews', 'HomeController@reviews')->name('reviews');
    Route::get('/support', 'HomeController@support')->name('support');
    Route::get('/about', 'HomeController@about')->name('about');
    Route::get('/legal-doc', 'HomeController@legalDoc')->name('legal.doc');
    Route::get('/news', 'HomeController@news')->name('news');
    Route::get('/full-text', 'HomeController@full_text')->name('full-text');
    Route::get('/card', 'HomeController@card')->name('card');
    Route::get('/statistics', 'HomeController@statistics')->name('statistics');
    Route::get('/anti-spam', 'HomeController@antiSpam')->name('anti.spam');
    Route::get('/policy', 'HomeController@policy')->name('policy');
    Route::get('/check_email', 'HomeController@check_email')->name('check_email');

    Route::post('save-comment', 'CommentController@store')->name('save.comment');
    Route::post('send-question-in-mail', 'HomeController@sendQuestionInMail')->name('send.question.mail');
    Route::post('send-modal-form', 'HomeController@sendModalForm')->name('send.modal.form');

    Route::group(['prefix' => 'account', 'middleware' => 'auth'], function () {

        Route::get('/profile', 'AccountController@index')->name('account');
        Route::get('/deposit-history', 'AccountController@depositHistory')->name('deposit.list');
        Route::get('/invest-history', 'AccountController@investHistory')->name('invest.list');
        Route::get('/payment-history', 'AccountController@paymentHistory')->name('payment.list');
        Route::get('/referral', 'AccountController@referral')->name('referral');
        Route::get('/banners', 'AccountController@reklama')->name('banners');
        Route::get('/settings', 'AccountController@setting')->name('settings');
        Route::get('/card', 'AccountController@card')->name('card');

        Route::get('/invest', 'AccountController@invest')->name('invest');
        Route::get('/deposit', 'AccountController@deposit')->name('deposit');
        Route::get('/payment', 'AccountController@payment')->name('payment');

        Route::post('update-password', 'AccountController@updatePassword')->name('update.password');
        Route::post('update-pay-accounts', 'AccountController@updatePayAccounts')->name('update.pay.accounts');

    });
	
    Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
        Route::resource('plans', 'PlanController');
        Route::get('approve-comment/{comment}', 'CommentController@approve')->name('approve.comment');
        Route::get('delete-comment/{comment}', 'CommentController@destroy')->name('delete.comment');
        Route::get('comments', 'AccountController@moderationComments')->name('moderation.comments');
        Route::resource('deposit', 'DepositController');
//        Route::post('payment-output', 'PaymentController@paymentOutput')->name('payment.output');
        Route::get('users', 'AccountController@users')->name('users');
//change_all//		
        Route::get('change_all/{user}', 'AccountController@change_all')->name('change_all');
//change_all-end//		
        Route::get('statistics', 'AccountController@statistics')->name('statistics.admin');
        Route::post('statistics', 'AccountController@updateStatistics')->name('update.statistics');
        Route::post('statistics-input', 'AccountController@updateStatisticsInput')->name('update.statistics.last.input');
        Route::get('statistics-input', 'AccountController@statisticsInput')->name('statistics.last.input');
        Route::post('statistics-output', 'AccountController@updateStatisticsOutput')->name('update.statistics.last.output');
        Route::get('statistics-output', 'AccountController@statisticsOutput')->name('statistics.last.output');
        Route::get('change-status/{user}', 'AccountController@changeStatus')->name('change.status');
    });

    Route::get('/verification-email', 'AccountController@verificationEmail');

});
//*****************************SYSTEM PAY********************
/**
 *              PAYEER
 */

Route::post('/pay-payeer', 'PaySystemController@PayeerInit');
Route::get('/pay-payeer-error', 'PaySystemController@PayeerError');
Route::get('/pay-payeer-success', 'PaySystemController@PayeerSuccess');
Route::get('/pay-payeer-status', 'PaySystemController@PayeerStatus');

/**
 *              PERFECT MONEY
 */
Route::post('/pay-perfect-money', 'PaySystemController@Perfect_MoneyInit');
Route::get('/pay-perfect-money-error', 'PaySystemController@Perfect_MoneyError');
Route::get('/pay-perfect-money-success', 'PaySystemController@Perfect_MoneySuccess');

/**
 *              Advanced Cash
 */
Route::post('/pay-adv-cash', 'PaySystemController@AdvCashInit');
Route::get('/pay-adv-cash-error', 'PaySystemController@AdvCashError');
Route::get('/pay-adv-cash-success', 'PaySystemController@AdvCashSuccess');
Route::get('/pay-adv-cash-status', 'PaySystemController@AdvCashStatus');

/*				FREE-KASSA							*/

Route::get('/fk-error', 'PaySystemController@FkError');
Route::get('/fk-success', 'PaySystemController@FkSuccess');
Route::get('/fk-status', 'PaySystemController@FKStatus');


//*********************************************************************

Route::post('upload-avatar', 'AccountController@UploadAvatar')->name('upload.avatar');
Route::post('add-deposit', 'AccountController@AddDeposit')->name('add.deposit');
Route::post('add-top', 'AccountController@AddTop')->name('add.top');
Route::post('add-other', 'AccountController@AddRefOther')->name('add.other');
Route::post('add-ref', 'AccountController@AddRef')->name('add.ref');
Route::post('edit-profile', 'AccountController@EditProfile')->name('edit.profile');
Route::post('payment-output', 'PaymentController@paymentOutput')->name('payment.output');

/* Cron */
Route::get('/cron-run-percent-793196380', 'PercentController@runPercent');
Route::get('/send_mail', 'AccountController@runSend');

resources/views/partial/components/_investment.blade.php
<div class="investment {{($_SERVER['REQUEST_URI']=='/' || $_SERVER['REQUEST_URI']=='/ru' || $_SERVER['REQUEST_URI']=='/de' || $_SERVER['REQUEST_URI']=='/en') ? '' : 'investment_inner'}}" id="invest">
    <div class="container">
        <input type="hidden" value="{{getJsonPlans()}}" name="js_plans" id="js_plans">
        <h3>@lang('my-text.key_42')</h3>
        <div class="calculator" data-step="10" data-intro="<h4>{{__('my-text.key_16')}}</h4><p>
                            {{__('my-text.key_17')}}</p>"
             data-highlightclass="menu-highlight" data-position="bottom">
            <div class="input_box" data-step="11"
                 data-intro="<h4>{{__('my-text.key_18')}}</h4><p>{{__('my-text.key_19')}}</p>"
                 data-highlightclass="menu-highlight" data-position="bottom">
                <label for="plan">@lang('my-text.key_28')</label>
                <div class="select_box">
                    <select name="plan" id="js-plan" class="form-control">
                        <option value selected>@lang('my-text.key_29')</option>
                        @foreach(getPlans() as $key => $plan)
                        <div>
                            <option value="{{++$key}}">
                               {{$plan->title}}
                            </option>
                        </div>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="input_box" data-step="12"
                 data-intro="<h4>{{__('my-text.key_20')}}</h4><p>{{__('my-text.key_21')}}</p>"
                 data-highlightclass="menu-highlight" data-position="bottom">
                <label for="amount">@lang('my-text.key_30')</label>
                <input type="number" id="js-amount" name="amount">
            </div>
            <div class="input_box" data-step="13" data-intro="<h4>{{__('my-text.key_22')}}</h4><p>
                            {{__('my-text.key_23')}}</p>"
                 data-highlightclass="menu-highlight" data-position="bottom">
                <label>@lang('my-text.key_31') </label>
                <div id="js-profit" class="count_box"></div>
            </div>
            <div class="input_box" data-step="14" data-intro="<h4>{{__('my-text.key_24')}}</h4><p>
                        {{__('my-text.key_25')}}</p>"
                 data-highlightclass="menu-highlight" data-position="bottom">
                <label>@lang('my-text.key_32')</label>
                <div id="js-total" class="count_box"></div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="list_carousel" data-step="9" data-intro="<h4>{{__('my-text.key_26')}}</h4><p>{{__('my-text.key_27')}}</p>" data-highlightclass="menu-highlight"
             data-tooltipclass="centered-tooltip" data-position="top">
            <ul id="foo2">
                @foreach(getPlans() as $plan)
                    <li class="invest_item forDate" id="{{$plan->title}}" data-name="{{$plan->title}}" data-percent="{{$plan->percent}}">
                    <div class="bottle_tittle">
                        {{--<div class="marker_choice marker_green">--}}
                            {{--<span class="popular_marker">Popular</span>--}}
                        {{--</div>--}}
                        <span style="font-weight: 900">{{$plan->title}}</span>
                    </div>
                    <div class="percent_number">{{$plan->percent}}%</div>
                        <div class="days_info my_sett">@lang('my-text.key_33') <span class="forDays">{{$plan->day}} @lang('my-text.key_34') </span></div>
                    <div class="general_info" style="width: 230px;">
                        <div>
                            <b style="font-weight: 900">@lang('my-text.key_35')</b>
                            <span>{{$plan->from_amount}}</span>
                        </div>
                        <div>
                            <b style="font-weight: 900">@lang('my-text.key_36')</b>
                            <span>{{$plan->to_amount}}</span>
                        </div>
                        <div>
                            <b style="font-weight: 900">@lang('my-text.key_37') <span>@lang('my-text.key_38')</span></b>
                        </div>
                        <div>
                            <b style="font-weight: 900">@lang('my-text.key_39') <span>@lang('my-text.key_40')</span></b>
                        </div>
                    </div>
                    <a href="{{route('deposit')}}" class="deposit_button">@lang('my-text.key_41')</a>
                </li>
                @endforeach
            </ul>
            <div class="clearfix"></div>
            <a class="nav_btn prev" href="#"></a>
            <a class="nav_btn next" href="#"></a>
        </div>
    </div>
</div>

resources/views/partial/components/left_menu.blade.php
        <!-- Left Panel
        ============================================= -->
        <aside class="col-lg-3"> 
          
          <!-- Profile Details
          =============================== -->
          <div class="bg-white shadow-sm rounded text-center p-3 mb-4">
            <div class="profile-thumb mt-3 mb-4"> <img class="rounded-circle" width="100" height="100" src="{{ asset('components/images/def-avatar.png') }}" alt="">
<!--
              <div class="profile-thumb-edit custom-file bg-primary text-white" data-toggle="tooltip" title="Change Profile Picture"> 
				<i class="fas fa-camera position-absolute"></i>
				<form enctype="multipart/form-data" id="upload_form" role="form" method="POST" action="{{route('upload.avatar')}}" >
					{{ csrf_field() }}
					<input type="file" class="custom-file-input" name="new_avatar" id="new_avatar">
				</form>
              </div>
-->			  
            </div>
            <p class="text-3 font-weight-500 mb-2">@lang('my-text.hi'), {{ auth()->user()->name }}</p>
<!--
            <p class="mb-2"><a href="profile.html" class="text-5 text-light" data-toggle="tooltip" title="Edit Profile"><i class="fas fa-edit"></i></a></p>
-->
          </div>
          <!-- Profile Details End --> 
          
          <!-- Available Balance
          =============================== -->
          <div class="bg-white shadow-sm rounded text-center p-3 mb-4">
            <div class="text-17 text-light my-3"><i class="fas fa-wallet"></i></div>
			@if(auth()->user()->custom_profile == 1)
				<h3 class="text-9 font-weight-400">${{ number_format(auth()->user()->detail->amount, 2, '.', '') . ' ' }}</h3>
			@else
				<h3 class="text-9 font-weight-400">${{ number_format(auth()->user()->detail->amount, 2, '.', '') . ' ' }}</h3>
			@endif
            <p class="mb-2 text-muted opacity-8">@lang('my-text.key_364')</p>
          </div>
          <!-- Available Balance End --> 
          <div class="col-12 mb-4">
			  <div class="row">
				  <button type="button" class="col-lg-12 btn btn-primary btn-sm mb-1" onclick="window.location.href='{{route('invest')}}'">@lang('my-text.key_50')</button>
				  <button type="button" class="col-lg-12 btn btn-primary btn-sm mb-1" onclick="window.location.href='{{route('deposit')}}'">@lang('my-text.deposit')</button>
				  <button type="button" class="col-lg-12 btn btn-primary btn-sm" onclick="window.location.href='{{route('payment')}}'">@lang('my-text.key_52')</button>
			  </div>
		  </div>
		  
          <!-- Need Help?
          =============================== -->
          <div class="bg-white shadow-sm rounded text-center p-3 mb-4">
            <div class="text-17 text-light my-3"><i class="fas fa-comments"></i></div>
            <h3 class="text-5 font-weight-400 my-4">@lang('my-text.help')</h3>
            <p class="text-muted opacity-8 mb-4">@lang('my-text.help_text')</p>
            <a href="{{route('support')}}#support" class="btn btn-primary btn-block">@lang('my-text.help_btn')</a> </div>
          <!-- Need Help? End --> 
          
        </aside>
        <!-- Left Panel End --> 

resources/views/partial/components/left_menu_admin.blade.php
<div class="left_menu" style="height: 500px">
    <h3 style="color: darkred; font-weight: 600">@lang('my-text.key_69')</h3>
    <ul class="left_navigation_menu">
        <li class="menu-item">
            <a href="{{route('plans.index')}}">
                <i class="fa" aria-hidden="true"></i>
                <span>@lang('my-text.key_70')</span>
            </a>
        </li>
        <li class="menu-item">
            <a href="{{route('moderation.comments')}}">
                <i class="fa" aria-hidden="true"></i>
                <span>@lang('my-text.key_71')</span>
            </a>
        </li>
        <li class="menu-item">
            <a href="{{route('users')}}">
                <i class="fa" aria-hidden="true"></i>
                <span>@lang('my-text.key_72')</span>
            </a>
        </li>
        <li class="menu-item">
            <a href="{{route('statistics.admin')}}">
                <i class="fa" aria-hidden="true"></i>
                <span>@lang('my-text.key_73')</span>
            </a>
        </li>
        <li class="menu-item">
            <a href="{{route('statistics.last.input')}}">
                <i class="fa" aria-hidden="true"></i>
                <span>@lang('my-text.key_74')</span>
            </a>
        </li>
        <li class="menu-item">
            <a href="{{route('statistics.last.output')}}">
                <i class="fa" aria-hidden="true"></i>
                <span>@lang('my-text.key_75')</span>
            </a>
        </li>
    </ul>
</div>